spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/shiro?useSSL=true
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      percentage: 1

zipkin:
  storage:
    type: mysql

logging:
  level:
    org.springframework.cloud.netflix.feign: debug