spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/hxiugangxh/config-repo.git
          username: huxiugangxh
          password: fafafa
#          basedir: D:\hxg\gongsi\hxg-spring-cloud\config\src\main\resources\basedir
          search-paths: '{application}'
          force-pull: true
management:
  endpoints:
    web:
      expose: "*"
  security:
    enabled: false