spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: ylzinfo
    url: jdbc:mysql://192.168.43.33:3306/elk?useSSL=true
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      percentage: 1
logging:
  level:
    org.springframework.cloud.netflix.feign: debug